import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ApolloProviderWrapper from "@/components/ApolloProviderWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProviderWrapper>
          <UserProvider>{children}</UserProvider>
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
